name: Webhook Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  repository_dispatch:
    types: [ webhook-trigger ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Print updated Item
        run: echo "${{ github.event.client_payload.item }}"

      - name: Print updated Vault
        run: echo "${{ github.event.client_payload.vault }}"
