name: Webhook Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  repository_dispatch:
    types: [ webhook-trigger ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Print webhook description
        run: echo "Description from webhook: ${{ github.event.client_payload.description }}"

